### ISSUE TITLE
Has the data set BlogCatalog been processed?

### ISSUE THREAD

**Issue by Junshuai-Song** [aditya-grover/node2vec#12]
Has the data set BlogCatalog been processed?

The data set BlogCatalog here(http://socialcomputing.asu.edu/datasets/BlogCatalog3)  is different from the one used in deepwalk(https://github.com/phanein/deepwalk).

the data set BlogCatalog downloaded here:
10306,39
10307,39
10308,39
10309,39
10310,39
10311,39
10311,39
10312,39 
from "group-edges.txt".

the data set BlogCatalog downloaded from http://leitang.net/social_dimension.html (which is used in deepwalk):
    (14,39)             
  (691,39)             
(1250,39)             
(1344,39)             
(1465,39)             
(1550,39)             
(4709,39)             
(7759,39) 

For category 39, there are obvious differences, are these two different data sets?

**Comment by songjs1993** [comment]
The label attribute in these two data set is different(the network seems the same).

**Comment by Junshuai-Song** [comment]
I have found the reason. I directly changed the file suffix (.csv -> .txt, downloaded from http://socialcomputing.asu.edu/datasets/BlogCatalog3), and it caused some mistakes.
