### ISSUE TITLE
node2vec on Zachary's karate club network

### ISSUE THREAD

**Issue by saimmehmood** [aditya-grover/node2vec#23]
After running the following command:
`python src/main.py --input graph/karate.edgelist --output emb/karate.emd`

I am receiving this error:
Walk iteration:
1 / 10
2 / 10
3 / 10
4 / 10
5 / 10
6 / 10
7 / 10
8 / 10
9 / 10
10 / 10
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    main(args)
  File "src/main.py", line 100, in main
    learn_embeddings(walks)
  File "src/main.py", line 87, in learn_embeddings
    model = Word2Vec(walks, size=args.dimensions, window=args.window_size, min_count=0, sg=1, workers=args.workers, iter=args.iter)
TypeError: __init__() got an unexpected keyword argument 'iter'

**Comment by tarunkumariitm** [comment]
In src/main.py change line #87 to:
`model = Word2Vec(walks, size=args.dimensions, window=args.window_size, min_count=0, sg=1, workers=args.workers)
`

After that, add the following line:
`model.iter = args.iter
`

**Comment by saimmehmood** [comment]
Thank you @tarunkumariitm
