### ISSUE TITLE
MIT/Apache License

### ISSUE THREAD

**Issue by EntilZha** [aditya-grover/node2vec#5]
I am working on improving the speed/parallelization of node2vec for a research project I am working on to see if it can be used for question answering via the wikipedia network structure (https://github.com/Pinafore/qb), and noticed that the source code doesn't have a license.

Would it be possible for you to add a permissive license like MIT/Apache so there are no worries about that later?

**Comment by roks** [comment]
We have a parallel implementation of node2vec in C++ as part of SNAP, which you might want to check out. It is available here:
https://github.com/snap-stanford/snap/tree/master/examples/node2vec

**Comment by EntilZha** [comment]
Thanks for pointing that out. Is there any guidance on parameter tuning by chance or should I send a message separately to you/author?

**Comment by aditya-grover** [comment]
Added the license file. You can find some basic parameter tuning guidance in the experiments section of the accompanying paper here: [https://arxiv.org/abs/1607.00653]
