### ISSUE TITLE
TypeError: 'float' object is not iterable   : Failed to convert edge data (['0.0000055313498705800166']) to dictionary.

### ISSUE THREAD

**Issue by ghost** [aditya-grover/node2vec#53]
hi～
I am attempting to creating a weighted graph, and the weight down to e-9, but does not works
![image](https://user-images.githubusercontent.com/38690421/49351652-6a8c5b00-f6ef-11e8-8674-8954eefb93c2.png)
while I convert it to string,  either 
![image](https://user-images.githubusercontent.com/38690421/49352230-e1c2ee80-f6f1-11e8-9e08-9161e84f9434.png)
![image](https://user-images.githubusercontent.com/38690421/49352118-7ed15780-f6f1-11e8-904f-2f09fbcc1ea2.png)

anyone know why?

**Comment by spitis** [comment]
You need to add "--weighted" argument.
