### ISSUE TITLE
Seed functionality

### ISSUE THREAD

**Issue by ttuygun** [aditya-grover/node2vec#62]
Is there a way to adding seeding functionality in order to produce same result for debugging/testing purposes?

We try to seed before every rand function call but it produces different results in every run.
```python
def simulate_walks(self, num_walks, walk_length):
...
    random.seed(self.random_state)
    random.shuffle(nodes)
...
```

```python
def alias_draw(J, q, random_state):
...
    np.random.seed(random_state)
    kk = int(np.floor(np.random.rand()*K))
...
    np.random.seed(random_state)
    if np.random.rand() < q[kk]:
...
```

Is there anything that we missed?

**Comment by DozenCoder** [comment]
Try to use same random seed？Such as:
```
random.seed(1)
```

**Comment by ttuygun** [comment]
Yes, I have already tried as

**Comment by ttuygun** [comment]
I've solved the problem. The problem related with the Word2Vec's workers count. [Gensim documentation](https://radimrehurek.com/gensim/models/word2vec.html) said that we need to set `workers=1` in order to generate reproducible run.
> Note that for a fully deterministically-reproducible run, you must also limit the model to a single worker thread (workers=1)

**Comment by maxaalexeeva** [comment]
Hi, @ttuygun! Does 'same result' in case of node2vec mean you get exactly same embeddings for each node? Thank you!

**Comment by ttuygun** [comment]
> Hi, @ttuygun! Does 'same result' in case of node2vec mean you get exactly same embeddings for each node? Thank you!

Yes, exactly

**Comment by maxaalexeeva** [comment]
@ttuygun, thank you!
