### ISSUE TITLE
How to do negative sampling for skip-gram in data processing of spark version?

### ISSUE THREAD

**Issue by formath** [aditya-grover/node2vec#64]

**Comment by DozenCoder** [comment]
spark word2vec do not support negative sampling, only implemented hierarchical softmax.
<https://spark.apache.org/docs/2.3.2/mllib-feature-extraction.html#word2vec>

**Comment by formath** [comment]
Thanks. After random walk, we can use skip gram to generate pair `<src_node, positive_node>`. How to sample `negative nodes` for each pair in data processing phase while not in the training phase.
