### ISSUE TITLE
no output file??!

### ISSUE THREAD

**Issue by nabil215** [aditya-grover/node2vec#94]
hello when i run the script it show me that it went normal :
Walk iteration:
1 / 10
2 / 10
3 / 10
4 / 10
5 / 10
6 / 10
7 / 10
8 / 10
9 / 10
10 / 10

but i got no output file 
any help please

**Comment by pengince** [comment]
see this [issue](https://github.com/aditya-grover/node2vec/issues/11)

**Comment by nabil215** [comment]
thanks it's was just a syntax error

**Comment by amitmishramtech** [comment]
@nabil215 i am also having same issue. No Output file. how did you got solution? please help me.
